### PR TITLE
New Project Proposal: IoT Audit Checker

### PR DESCRIPTION
**Pull request by nescampos**

### CODE REVIEW

**Comment by Fingerling42** [comment]
Hi, Nestor.

Thank you for participating in our grant program! Our team has started reviewing your proposal. We will give feedback in comments, stay tuned.

So far, there are two questions: 
1) Do you mind to talk with us on online meeting in future?
2) Could you tell how you found out about our grant program?

**Comment by nescampos** [comment]
Hi Ivan,
Thanks for your message. About the questions:

1.  Yes, I can talk with you when you want.
2.  I found out about the grant program by exploring the Robonomics documentation (seeing all the functionalities). I discovered and saw Robonomics at the hackathon you did at Devpost a few months ago, but I was unable to participate due to timing issues.

**Comment by Fingerling42** [comment]
Hi, Nestor. Here is our feedback. 

There is some interest for us to see an alternative scenario when Robonomics is used not at the sensor level, but as a system for auditing the results of their activities. However, we launched the program quite recently and are primarily looking for projects with a more direct connection with the Robonomics ecosystem, in its original idea.  Nevertheless, we would not like to leave your project unattended. Therefore, there are several points with questions and based on them we will continue to discuss the possibility of providing a grant.
- In the budget under "Platform programming", you indicated "development of the bookstore". Could you please clarify what you mean here? It is also not completely clear why platform programming has a part with showing in the meetup groups.
- There is also one more point. You indicate 7 months of platform programming, but the project schedule has a period from August to October-November for this task. Therefore, it is not entirely clear how you estimated the amount of development work.
- In general, we would like to reduce the project duration to 5 months. Judging by the resume, you have a very high level of competence in IoT and Microsoft Azure, and in our opinion, the main work will be in the development of dApp, and in fact this is a simpler task.
- So, we see the project schedule more like this: about a month for active development, 3 months for finalizing and generating content, and a month for events. 
- Adjusted budget accordingly:
Platform development — 12 000 USD.
Writing the project documentation — 5000 USD.
Tutorial recording — 6000 USD.
Events — 6000 USD
Total: 29 000 USD.

There is no need to convert the amount to ETH now (we will convert it at the time of proposal approval), just indicate your preferred cryptocurrency.

Also note that the grant is being given through a vesting mechanism (described in the Terms and Instruction section) and we will watch the progress of the project, especially the commits in the project repository.

Please consider these points and let us know what you think.

**Comment by Fingerling42** [comment]
PS;
You can also consider an option with some changes in the project for a specific scenario, with greater applicability of Robonomics. We can discuss this next week.

**Comment by nescampos** [comment]
Hello Ivan,
Thanks for the feedback. 
I agree with the changes in terms of amount and months. This weekend I am going to update the proposal so that it is more specific with your comments.

Thank you very much again for the feedback and the opportunity.
Néstor

**Comment by Fingerling42** [comment]
Hi, Nestor. 

My colleagues made an advice for a small technical addition to the proposal. This will help to better involve Robonomics in the project and make it more suitable for us.

From the description, the analyst of data from sensors is highlighted for users on some dashboard / app. We see further signing of this data using Robonomics in this way: since we use the IPFS + blockchain for data logging, we suggest you add such a function to the app. I.e., the user selects in the dapp the function of migrating analyzed data from Azure to IPFS (in the archive, for example). Further, at the user's command, the IPFS hash is used for data logging in the blockchain by means of Robonomics, thus signing the data.

If you take into account this advice and previous fixes on the schedule / budget, then the members of the Robonomics team will support the project.

**Comment by nescampos** [comment]
Hi Ivan,
Sure, I am going to consider the last feedback too in my proposal.
Thanks,
Néstor

**Comment by Fingerling42** [comment]
Hi, Nestor.

Can we expect an update of the proposal? Or have you decided to pause the idea for now?

**Comment by nescampos** [comment]
Hi Ivan,
I think it would be good (if it is feasible) to pause the proposal.
I already took all the feedback you sent me, but I'm talking to a partner because I think we can present you with something more detailed and of real impact.
Is it possible that I send the proposal again in a couple of months?
Thanks in advance and much success.
Best,
Néstor

**Comment by Fingerling42** [comment]
Hi, Nestor.

No problem, come back when you're ready. I close this request, we will wait for a new one from you. Good luck!

**Pull request closed without merging**
