### PR TITLE
Create Robochemist.md

### PR DESCRIPTION
**Pull request by zeeshanyousaf094**

### CODE REVIEW

**Comment by Fingerling42** [comment]
Hi Zeeshan!

Thank you for your interest in our program! The Robonomics team has started reviewing the proposal, stay tuned.

**Comment by Fingerling42** [comment]
Hi Zeeshan!

Here are the comments from the Robonomics team on the proposal:

- The role of Robonomics Network in the project is not entirely clear. In the sense, why is Robonomics needed here, what is its true advantage for such a project? In item 2 in the Project Overview, this point is described in too general terms to make a final conclusion of applicability.
- In addition to the previous question, the team thinks that right now the proposal has poorly described technical details, especially in the part of Robonomics. Of course, before the start of development, it is difficult to describe all the nuances, so the team proposes to correct the proposal as follows: split the project into 4-5 stages (starting with system design) and prepare a delivery map of the grant results. This, among other things, will help to correctly develop a plan of the technical components and its connection with Robonomics.
- Also, the team proposes to split funds according to these stages, and receive them after the implementation of each of stages.
- According to the schedule, you plan to complete the project in about 4 months. It seemed to the team that this might not be enough. Could you elaborate more on how you plan to finish the project in such a short time? Do you have any drafts or preparations? If yes, then this point should also be reflected in the proposal. Also, if possible, could you share links to your previous projects or repositories with projects of your colleagues?
- The team proposes to change the preferred cryptocurrency from DAI to XRT, if possible. Then it will even be easier to withdraw crypto (for example, you can exchange XRT on [Huobi](https://www.huobi.com/) and withdraw there). Please, tell us what you think about this option.

**Comment by Fingerling42** [comment]
Hi Zeeshan!

Do you still want to update the proposal? Maybe you need more time? If so, I will close the request and you can return to the grant program later, and re-send it.

**Comment by zeeshanyousaf094** [comment]
We got engaged in other project. 
Will connect back after some time and will reopen the request soon.

Thanks to the team for your time, see you soon.

**Pull request closed without merging**
