### PR TITLE
sensorchain_security_interface Application

### PR DESCRIPTION
**Pull request by SaschaKaven**

### CODE REVIEW

**Comment by Fingerling42** [comment]
Hi Sascha!

Thanks for your attention to our grant program. Our team will definitely start reviewing your application in the coming week.

But I noticed that you were using an old template from the first round of program. Can you please rework a little you proposal with new template? The main changes are in the Technical Details and Additional Information sections and for the preferred cryptocurrency.

https://github.com/airalab/robonomics-grant-program/blob/main/proposals/proposal-template.md

**Comment by SaschaKaven** [comment]
Thank you for the information.
I am going to submit the revised application by the beginning of next week.

**Comment by SaschaKaven** [comment]
Dear Robonomics Team,
I have now updated the application.
I am looking forward to your feedback.

**Comment by Fingerling42** [comment]
Hi Sascha!
I checked your proposal and there are a few things that need to be fixed before I send the proposal to Robonomics DAO:
- Administrative Information: "Organisation Name" was replaced with the second "Project Name", please return it. 
- Can you please describe in "8. Additional Information" the source from which you found out about the grant program?

**Comment by SaschaKaven** [comment]
Thank you for the feedback. 
I have included the requested improvements.

**Comment by Fingerling42** [comment]
Hi Sascha. 

The DAO reviewed the proposal and made several comments.

1) The DAO believes that the proposal could be significantly strengthened, and to this end suggests to consider replacing the Lego NXT with something more powerful. It is very likely that the Robonomics stack will not be able to work purely with NXT (for the full stack, the recommended system requirements correspond to Raspberry Pi 4B). Of course, this will require revising the project budget. Please write what you think about it and if you have any ideas for other mobile robots.

2) The team raised concerns about the volume of work and the number of participants in the project. Judging by the description, there is already a theoretical basis and some preliminary developments for the project, and the number of participants is only 2 people. Since almost the maximum amount has been requested for the project, and the period is 9 months, the team does not fully understand the complexity of project implementation. Could you more accurately describe the scope of work and what caused the requested amount of the grant and the timing?

3) About the cost of transactions to the network. 1 XRT is enough for 4,500 transactions in total, so you may need to reconsider the costs for them. Judging by the budget, you are going to create over 1 million transactions.

**Comment by Fingerling42** [comment]
Hi Sascha.

Any updates on proposal? If you need more time, I will close pull request and you can return later with new one.

**Comment by SaschaKaven** [comment]
Hello,

we are in the final stages of the revision and plan to submit the application this week.

**Comment by SaschaKaven** [comment]
Hello Ivan,

I hope you had a good start into the new year.
I have just revised the project schedule and adjusted it to a start in February.
Is there any info when we can expect feedback?

Best regards,

Sascha Kaven

**Comment by Fingerling42** [comment]
Hi Sascha!

Thanks for update. I hope, that the team will give the answer this-next week. 

Best,
Ivan

**Comment by Fingerling42** [comment]
Hi Sascha!

The team has discussed the changes of the proposal, and everyone is generally positive. Soon DAO will create a voting process and in a few days the results will be known.

Best,
Ivan

**Pull request merged**
